# Generated by Django 4.2.1 on 2023-05-30 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to add a created_at field to offer version
    """

    dependencies = [("cms", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="offerversion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
