# Generated by Django 4.2.1 on 2023-05-15 09:56

import django.core.files.storage
from django.db import migrations, models

import integreat_compass.cms.models.offers.document


class Migration(migrations.Migration):
    dependencies = [("cms", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/johannes/integreat-compass/integreat_compass/media"
                ),
                upload_to="documents/",
                validators=[
                    integreat_compass.cms.models.offers.document.file_size_limit
                ],
                verbose_name="file",
            ),
        )
    ]
